app.artist.get:
  path: "/{id}"
  defaults: { _controller: App\Controller\V4\Artist\ArtistController::getAction }
  methods: [GET]

app.artist.index:
  path: "/"
  defaults: { _controller: App\Controller\V4\Artist\ArtistController::indexAction }
  methods: [GET]
