app.lyric.get:
  path: "/{id}"
  defaults: { _controller: App\Controller\V4\Lyric\LyricController::getAction }
  methods: [GET]

app.lyric.index:
  path: "/"
  defaults: { _controller: App\Controller\V4\Lyric\LyricController::indexAction }
  methods: [GET]
