global_exclude_dirs:
    - vendor
    - Test
    - app/scripts/cron
    - src/Tekstove/ApiBundle/Model/Base/

exclude_patterns:
    - app/config/parameters_travis.yml
    - app/check.php
    - src/Tekstove/ApiBundle/Model/*/Base/*
    - src/Tekstove/ApiBundle/Model/*/Map/*

php_version: 7
