language: php
php:
  - 7.4
  - nightly

before_script:
  - phpenv rehash

script:
    - composer install -d tests/codeSniffer/
    - ./tests/codeSniffer/vendor/bin/phpcs --standard=tests/codeSniffer/phpcs.xml
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist
    - ./vendor/bin/phpunit -c tests/phpunit/phpunit.xml --no-coverage
    - ./bin/console doctrine:mapping:info

matrix:
    allow_failures:
        - php: nightly

notifications:
    on_success: never
    on_failure: never
    on_change: never
