language: php
php:
  - 7.1
  - nightly

before_script:
  - phpenv rehash
#  - mv app/config/parameters_travis.yml app/config/parameters.yml
#  - mysql -e 'create database tekstove_lyric;'

script:
    - composer install -d Test/codeSniffer/
    - Test/codeSniffer/vendor/bin/phpcs --standard=Test/codeSniffer/phpcs.xml src/
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - composer install --prefer-dist
    - vendor/bin/phpunit -c Test/Phpunit/phpunit.xml --no-coverage 

matrix:
    allow_failures:
        - php: nightly

notifications:
    on_success: never
    on_failure: always
    on_change: always
