# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        tekstove.api.user_provider:
            id: tekstove.api.user_provider
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            stateless: true
            anonymous: ~
            simple_preauth:
                authenticator: tekstove.api.apikey_authenticator
            provider: tekstove.api.user_provider
