"App\\Entity\\Artist\\Artist":
  exclusion_policy: all
  exclude: false
  read_only: true
  virtual_properties:
    getId:
      serialized_name: id
      groups: ['list', 'details']
    getName:
      serialized_name: name
      groups: ['list', 'details']
