"App\\Entity\\Lyric\\Lyric":
  exclusion_policy: all
  exclude: false
  read_only: true
  virtual_properties:
    getId:
      groups: ['list', 'details']
      serialized_name: id
    getTitle:
      groups: ['list', 'details']
      serialized_name: title
    getArtistLyrics:
      groups: ['details']
      serialized_name: artists
    getText:
      groups: ['details']
      serialized_name: text
    getTextBg:
      groups: ['details']
      serialized_name: textBg
    getViews:
      groups: ['details']
      serialized_name: views
    getPopularity:
      groups: ['details']
      serialized_name: popularity
    getVideoVbox7:
      groups: ['details']
      serialized_name: videoVbox7
    getExtraInfo:
      groups: ['details']
      serialized_name: extraInfo
    isManualCensored:
      groups: ['details']
      serialized_name: manualCensor
    isCensored:
      groups: ['details']
      serialized_name: censor
    isForbidden:
      groups: ['details']
      serialized_name: forbidden
    getLanguages:
      groups: ['details']
      serialized_name: languages
    getSendBy:
      groups: ['lyric.sendBy']
      serialized_name: sendBy
    getSendDate:
      groups: ['details']
      serialized_name: sendDate
      type: DateTime<'U'>
