App\Entity\Lyric\Lyric:
  attributes:
    id:
      groups: ['list']
    title:
      groups: ['list']
    sendDate:
      groups: ['details']
    text:
      groups: ['details']
    forbidden:
      groups: ['list', 'details']
    artistLyrics:
      groups: ['details']
