tekstove_api_user:
    path: "/users"
    defaults: { _controller: TekstoveApiBundle:User:index }
    methods: [GET]

tekstove_api_user_register_index:
    path: "/users/register"
    defaults: { _controller: TekstoveApiBundle:User/Register:index }
    methods: [GET]
    
tekstove_api_user_register_post:
    path: "/users/register"
    defaults: { _controller: TekstoveApiBundle:User/Register:post }
    methods: [POST]

tekstove_api_user_get:
    path: "/users/{id}"
    defaults: { _controller: TekstoveApiBundle:User:get }
    methods: [GET]

tekstove_api_user_login_post:
    path: "/users/login/{username}"
    defaults: { _controller: TekstoveApiBundle:User/Login:post }
    methods: [POST]

tekstove_api_user_credentials_list:
    path: "/users/credentials"
    defaults: { _controller: TekstoveApiBundle:UserCredentials:index }
    methods: [GET]

tekstove_api_user_credentials:
    path: "/users/credentials/{id}"
    defaults: { _controller: TekstoveApiBundle:UserCredentials:get }
    methods: [GET]
    
tekstove_api_lyric:
    path: "/lyrics"
    defaults: { _controller: TekstoveApiBundle:Lyric:index }
    methods: [GET]

tekstove_api_lyric_credentials:
    path: "/lyrics/credentials/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric\Credentials:index, id: ~ }
    methods: [GET]


tekstove_api_lyric_get:
    path: "/lyrics/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:get }
    methods: [GET]

tekstove_api_lyric_post:
    path: "/lyrics"
    defaults: { _controller: TekstoveApiBundle:Lyric:post}
    methods: [POST]
    
tekstove_api_lyric_patch:
    path: "/lyrics/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:patch}
    methods: [PATCH]
    
tekstove_api_lyric.delete:
    path: "/lyrics/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:delete}
    methods: [DELETE]

tekstove_api_languages:
    path: /languages
    defaults: { _controller: TekstoveApiBundle:Language\Languages:index }
    
tekstove_api_artist:
    path: "/artists"
    defaults: { _controller: TekstoveApiBundle:Artist:index }
    methods: [GET]

tekstove_api_artist.get:
    path: "/artists/{id}"
    defaults: { _controller: TekstoveApiBundle:Artist:get }
    methods: [GET]

tekstove_api_lyric_album_index:
    path: "/albums"
    defaults: { _controller: TekstoveApiBundle:Album:index, id: ~ }
    methods: [GET]
