tekstove_api_user:
    path: "/user"
    defaults: { _controller: TekstoveApiBundle:User:index }
    methods: [GET]

tekstove_api_user_credentials_list:
    path: "/user/credentials"
    defaults: { _controller: TekstoveApiBundle:UserCredentials:index }
    methods: [GET]

tekstove_api_user_credentials:
    path: "/user/credentials/{id}"
    defaults: { _controller: TekstoveApiBundle:UserCredentials:get }
    methods: [GET]

tekstove_api_lyric:
    path: "/lyric/list"
    defaults: { _controller: TekstoveApiBundle:Lyric:index }
    methods: [GET]
tekstove_api_lyric_get:
    path: "/lyric/get/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:get }
    methods: [GET]
