tekstove_api_chat_routing:
    resource: "@TekstoveApiBundle/Resources/config/routing/chat.yml"
    prefix:   /chat

tekstove_api_user_routing:
    resource: "@TekstoveApiBundle/Resources/config/routing/user.yml"
    prefix:   /users

tekstove_api_lyric_routing:
    resource: "@TekstoveApiBundle/Resources/config/routing/lyric.yml"
    prefix:   /lyrics

tekstove_api_forum_routing:
    resource: "@TekstoveApiBundle/Resources/config/routing/forum.yml"
    prefix:   /forum

tekstove_api_languages:
    path: /languages
    defaults: { _controller: TekstoveApiBundle:Language\Languages:index }
    methods: [GET]

tekstove_api_artist:
    path: "/artists"
    defaults: { _controller: TekstoveApiBundle:Artist:index }
    methods: [GET]

tekstove_api_artist.get:
    path: "/artists/{id}"
    defaults: { _controller: TekstoveApiBundle:Artist:get }
    methods: [GET]

tekstove_api_lyric_album_get:
    path: "/albums/{id}"
    defaults: { _controller: TekstoveApiBundle:Album:get }
    methods: [GET]

tekstove_api_lyric_album_index:
    path: "/albums"
    defaults: { _controller: TekstoveApiBundle:Album:index }
    methods: [GET]
