services:
    tekstove.api.serializer.subscriber:
        class: Tekstove\ApiBundle\EventListener\Model\Lyric\SerializationSubscriber
        tags:
            - { name: "jms_serializer.event_subscriber" }

    tekstove.api.serializer.autoacl_subscriber:
        class: Tekstove\ApiBundle\EventListener\Model\Serialize\AclSubscriber
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: "jms_serializer.event_subscriber" }

    tekstove.api.user_provider:
        class: Tekstove\ApiBundle\Security\ApiUserProvider

    tekstove.api.apikey_authenticator:
        class:  Tekstove\ApiBundle\Security\ApiKeyAuthenticator
        public: false
        
    tekstove.lyric.repository:
        class: Tekstove\ApiBundle\Model\LyricQuery
        calls:
            - [setEventDispacher, ["@tekstove.event_dispacher"]]
            - [setValidator, ["@validator"]]
            
    tekstove.user.repository:
        class: Tekstove\ApiBundle\Model\UserQuery
        calls:
            - [setEventDispacher, ["@tekstove.event_dispacher"]]
            - [setValidator, ["@validator"]]
    
    tekstove.user.pm.repository:
        class: Tekstove\ApiBundle\Model\User\PmQuery
        calls:
            - [setEventDispacher, ["@tekstove.event_dispacher"]]
            - [setValidator, ["@validator"]]

    tekstove.forum.topic.repository:
        class: Tekstove\ApiBundle\Model\Forum\TopicQuery
        calls:
            - [setEventDispacher, ["@tekstove.event_dispacher"]]
            - [setValidator, ["@validator"]]

    tekstove.forum.post.repository:
        class: Tekstove\ApiBundle\Model\Forum\PostQuery
        calls:
            - [setEventDispacher, ["@tekstove.event_dispacher"]]
            - [setValidator, ["@validator"]]
        
    tekstove.chat.message.repository:
        class: Tekstove\ApiBundle\Model\Chat\MessageQuery
        calls:
            - [setEventDispacher, ["@tekstove.event_dispacher"]]
            - [setValidator, ["@validator"]]
        
    tekstove.event_dispacher.factory:
        class: Tekstove\ApiBundle\EventDispatcher\EventDispacherFactory
        arguments: []
    
    tekstove.event_dispacher:
        class: Tekstove\ApiBundle\EventDispatcher\EventDispacher
        factory: ["@tekstove.event_dispacher.factory", createDispacher]
        arguments: ["@service_container"]


    tekstove.api.security.lyric_voter:
        class: Tekstove\ApiBundle\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
    tekstove.api.security.album.voter:
        class: Tekstove\ApiBundle\Security\Authorization\Voter\AlbumVoter
        public: false
        tags:
            - { name: security.voter }
