services:
    tekstove.api.serializer.subscriber:
        class: Tekstove\ApiBundle\EventListener\Model\Lyric\SerializationSubscriber
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: "jms_serializer.event_subscriber" }

    tekstove.api.serializer.autoacl_subscriber:
        class: Tekstove\ApiBundle\EventListener\Model\Serialize\AclSubscriber
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: "jms_serializer.event_subscriber" }

    tekstove.api.user_provider:
        class: Tekstove\ApiBundle\Security\ApiUserProvider

    tekstove.api.apikey_authenticator:
        class:  Tekstove\ApiBundle\Security\ApiKeyAuthenticator
        public: false
        
    tekstove.lyric.repository:
        class: Tekstove\ApiBundle\Model\Lyric\LyricRepository
        arguments: ["@tekstove.event_dispacher"]
        calls:
            - [setValidator, ["@validator"]]
            
    tekstove.user.repository:
        class: Tekstove\ApiBundle\Model\User\UserRepository
        arguments: ["@tekstove.event_dispacher"]
        calls:
            - [setValidator, ["@validator"]]
        
    tekstove.event_dispacher.factory:
        class: Tekstove\ApiBundle\EventDispatcher\EventDispacherFactory
        arguments: []
    
    tekstove.event_dispacher:
        class: Tekstove\ApiBundle\EventDispatcher\EventDispacher
        factory: ["@tekstove.event_dispacher.factory", createDispacher]
        arguments: ["@service_container"]


    tekstove.api.security.lyric_voter:
        class: Tekstove\ApiBundle\Security\Authorization\Voter\LyricVoter
        public: false
        tags:
            - { name: security.voter }
