tekstove_api_album_routing:
    resource: "routes/routing/album.yml"
    prefix:   /albums
    defaults: { _format: json }

tekstove_api_artist_routing:
    resource: "routes/routing/artist.yml"
    prefix:   /artists
    defaults: { _format: json }

tekstove_api_chat_routing:
    resource: "routes/routing/chat.yml"
    prefix:   /chat
    defaults: { _format: json }

tekstove_api_forum_routing:
    resource: "routes/routing/forum.yml"
    prefix:   /forum
    defaults: { _format: json }

tekstove_api_lyric_routing:
    resource: "routes/routing/lyric.yml"
    prefix:   /lyrics
    defaults: { _format: json }

tekstove_api_v4_lyric_routing:
    resource: "routes/routing/v4/lyric.yml"
    prefix:   /v4/lyrics
    defaults: { _format: json }

tekstove_api_user_routing:
    resource: "routes/routing/user.yml"
    prefix:   /users
    defaults: { _format: json }

tekstove_api_languages:
    path: /languages
    defaults: { _controller: App\Controller\Language\LanguagesController::indexAction, _format: json }
    methods: [GET]

