"Tekstove\\ApiBundle\\Model\\Forum\\Post":
    exclusion_policy: all
    exclude: false
    read_only: true
    virtual_properties:
        getId:
            groups: [Details, List]
            serialized_name: id
        getText:
            groups: [Details, List]
            serialized_name: text
        getDateTimeTimestamp:
            groups: [Details, List]
            serialized_name: datetime
        getUser:
            groups: [Details, Forum_Post_User]
            serialized_name: user
        getTopic:
            groups: [Details, Forum_Post_Topic]
            serialized_name: topic
