"Tekstove\\ApiBundle\\Model\\Base\\Lyric":
    exclusion_policy: none
    exclude: false
    read_only: true
    properties:
        id:
            groups: [List, Details]
        title:
            groups: [List, Details]
        text:
            groups: [Details]
        send_by:
            groups: [Details]
            serialized_name: sendBy
        views:
            groups: [Details]
        popularity:
            groups: [Details]
        cache_title_short:
            serialized_name: cacheTitleShort
            groups: [List]
