"Tekstove\\ApiBundle\\Model\\Base\\Artist":
    exclusion_policy: none
    exclude: false
    read_only: true
    properties:
        id:
            groups: [List, Details]
        name:
            groups: [List, Details]
