"Tekstove\\ApiBundle\\Model\\Chat\\Message":
    exclusion_policy: all
    exclude: false
    read_only: true
    virtual_properties:
        getId:
            groups: [Details, List]
            serialized_name: id
        getMessage:
            groups: [Details, List]
            serialized_name: message
        getMessageHtml:
            groups: [Details, List]
            serialized_name: messageHtml
        getDateTimeTimestamp:
            groups: [Details, List]
            serialized_name: date
        getIp:
            groups: [Details]
            serialized_name: ip
        getUser:
            groups: [Details]
            serialized_name: user
