"Tekstove\\ApiBundle\\Model\\Base\\User":
    exclusion_policy: none
    exclude: false
    read_only: false
    properties:
        username:
            expose: true
            groups: [List, Credentials]
        password:
            expose: false
            include: false
            groups: [Credentials]
        mail:
            expose: true
            groups: [Credentials]
        avatar:
            expose: true
            groups: [List]
