"Tekstove\\ApiBundle\\Model\\Lyric":
    exclusion_policy: none
    exclude: false
    read_only: true
    virtual_properties:
        acl:
            groups: [Acl]
        getOrderedArtists:
            groups: [Details]
            serialized_name: artists
        getLanguages:
            type: array<Tekstove\ApiBundle\Model\Language>
            groups: [Details]
            serialized_name: languages
        getTextBg:
            groups: [Details]
            serialized_name: textBg
        getVideoYoutube:
            groups: [Details]
            serialized_name: videoYoutube
        getVideoVbox7:
            groups: [Details]
            serialized_name: videoVbox7
