"Tekstove\\ApiBundle\\Model\\Forum\\Post":
    exclusion_policy: none
    exclude: false
    read_only: true
    virtual_properties:
        getId:
            groups: [Details, List]
            serialized_name: id
        getText:
            groups: [Details, List]
            serialized_name: text
        getDateTatetime:
            groups: [Details, List]
            serialized_name: datetime
        getUser:
            groups: [Details, Forum_Post_User]
            serialized_name: user
