"Tekstove\\ApiBundle\\Model\\Lyric":
    exclusion_policy: all
    exclude: false
    read_only: true
    virtual_properties:
        getId:
            groups: [List, Details]
            serialized_name: id
        getTitle:
            groups: [List, Details]
            serialized_name: title
        getText:
            groups: [Details]
            serialized_name: text
        getExtraInfo:
            groups: [Details]
            serialized_name: extraInfo
        getSendBy:
            groups: [List, Details]
            serialized_name: sendBy
        getViews:
            groups: [Details]
            serialized_name: views
        getPopularity:
            groups: [Details]
            serialized_name: popularity
        getCacheTitleShort:
            groups: [List, Details]
            serialized_name: cacheTitleShort
        acl:
            groups: [Acl]
            serialized_name: acl
        getOrderedArtists:
            groups: [Details]
            serialized_name: artists
        getLanguages:
            type: array<Tekstove\ApiBundle\Model\Language>
            groups: [Details]
            serialized_name: languages
        getTextBg:
            groups: [Details]
            serialized_name: textBg
        getVideoYoutube:
            groups: [Details]
            serialized_name: videoYoutube
        getVideoVbox7:
            groups: [Details]
            serialized_name: videoVbox7
        isForbidden:
            groups: [Details]
            serialized_name: forbidden
        isCacheCensor:
            groups: [Details]
            serialized_name: censor
