"Tekstove\\ApiBundle\\Model\\User\\Pm":
    exclusion_policy: all
    exclude: false
    read_only: false
    virtual_properties:
        getId:
            groups: [Details, List]
            serialized_name: id
        getTitle:
            groups: [Details, List]
            serialized_name: title
        getRead:
            groups: [Details, List]
            serialized_name: read
        getDateTimeTimestamp:
            groups: [Details, List]
            serialized_name: datetime
        getText:
            groups: [Details]
            serialized_name: text
        getUserRelatedByUserFrom:
            groups: [Details, List]
            serialized_name: userFrom
        getUserRelatedByUserTo:
            groups: [Details, List]
            serialized_name: userTo
