"Tekstove\\ApiBundle\\Model\\Lyric":
    exclusion_policy: none
    exclude: false
    read_only: true
    virtual_properties:
        acl:
            groups: [Acl]
        getOrderedArtists:
            groups: [Details]
            serialized_name: artists
