"Tekstove\\ApiBundle\\Model\\Acl\\PermissionGroup":
    exclusion_policy: all
    read_only: true
    virtual_properties:
        getId:
            groups: [Details, List]
            serialized_name: id
        getName:
            groups: [Details, List]
            serialized_name: name
        getImage:
            groups: [Details]
            serialized_name: image
