"Tekstove\\ApiBundle\\Model\\Artist":
    exclusion_policy: all
    exclude: false
    read_only: true
    properties:
        forbidden:
            groups: [Details]
    virtual_properties:
        getAlbums:
            groups: [Albums]
            serialized_name: albums
        getAbout:
            groups: [Details]
            serialized_name: about
