"Tekstove\\ApiBundle\\Model\\Forum\\Topic":
    exclusion_policy: none
    exclude: false
    read_only: true
    virtual_properties:
        getId:
            groups: [Details, List, Acl]
            serialized_name: id
        getName:
            groups: [Details, List]
            serialized_name: name
        getUser:
            groups: [Details]
            serialized_name: user
        getCategory:
            groups: [Details]
            serialized_name: category
        getLatestPost:
            groups: [LatestPost]
            serialized_name: latestPost
