"Tekstove\\ApiBundle\\Model\\Base\\User":
    exclusion_policy: none
    exclude: false
    read_only: false
    properties:
        id:
            groups: [List, Details]
        username:
            expose: true
            groups: [List, Credentials, Details]
        api_key:
            expose: false
            groups: [Credentials]
            serialized_name: apiKey
        password:
            expose: false
            include: false
            groups: []
        mail:
            expose: true
            groups: [Credentials]
        avatar:
            expose: true
            groups: [List, Details]
