tekstove_api_album_credentials_new_albums:
    path: "/credentials"
    defaults: { _controller: TekstoveApiBundle:Album\Credentials:index, id: ~ }
    methods: [GET]

tekstove_api_album_credentials:
    path: "/credentials/{id}"
    defaults: { _controller: TekstoveApiBundle:Album\Credentials:index }
    methods: [GET]

tekstove_api_album_get:
    path: "/{id}"
    defaults: { _controller: TekstoveApiBundle:Album:get }
    methods: [GET]

tekstove_api_album_index:
    path: "/"
    defaults: { _controller: TekstoveApiBundle:Album:index }
    methods: [GET]
