tekstove_api_album_get:
    path: "/{id}"
    defaults: { _controller: TekstoveApiBundle:Album:get }
    methods: [GET]

tekstove_api_album_index:
    path: "/"
    defaults: { _controller: TekstoveApiBundle:Album:index }
    methods: [GET]

