tekstove_api_chat_messages_index:
    path: "/messages"
    defaults: { _controller: TekstoveApiBundle:Chat\Messages:index }
    methods: [GET]

tekstove_api_chat_messages_post:
    path: "/messages"
    defaults: { _controller: TekstoveApiBundle:Chat\Messages:post }
    methods: [POST]

tekstove_api_chat_online_index:
    path: "/online"
    defaults: { _controller: TekstoveApiBundle:Chat\Online:index }
    methods: [GET]

tekstove_api_chat_online_post:
    path: "/online"
    defaults: { _controller: TekstoveApiBundle:Chat\Online:post }
    methods: [POST]
