tekstove_api_user:
    path: "/"
    defaults: { _controller: TekstoveApiBundle:User:index }
    methods: [GET]

tekstove_api_user_register_index:
    path: "/register/"
    defaults: { _controller: TekstoveApiBundle:User/Register:index }
    methods: [GET]
    
tekstove_api_user_register_post:
    path: "/register/"
    defaults: { _controller: TekstoveApiBundle:User/Register:post }
    methods: [POST]

tekstove_api_user_get:
    path: "/{id}"
    defaults: { _controller: TekstoveApiBundle:User:get }
    methods: [GET]
    requirements:
        id:  \d+

tekstove_api.user.patch:
    path: "/{id}"
    defaults: { _controller:  TekstoveApiBundle:User:patch}
    methods: [PATCH]

tekstove_api_user_login_post:
    path: "/login/"
    defaults: { _controller: TekstoveApiBundle:User\Login:post }
    methods: [POST]
    
tekstove_api_user_login_get:
    path: "/login"
    defaults: { _controller: TekstoveApiBundle:User\Login:get }
    methods: [GET]

tekstove_api_user_credentials_list:
    path: "/credentials/"
    defaults: { _controller: TekstoveApiBundle:UserCredentials:index }
    methods: [GET]

tekstove_api_user_credentials:
    path: "/credentials/{id}"
    defaults: { _controller: TekstoveApiBundle:UserCredentials:get }
    methods: [GET]
    
tekstove_api.user.pm.index:
    path: "/pm/"
    defaults: { _controller: TekstoveApiBundle:User\Pm:index }
    methods: [GET]
    
tekstove_api.user.pm.get:
    path: "/pm/{id}"
    defaults: { _controller: TekstoveApiBundle:User\Pm:get }
    methods: [GET]

tekstove_api.user.pm.patch:
    path: "/pm/{id}"
    defaults: { _controller:  TekstoveApiBundle:User\Pm:patch}
    methods: [PATCH]
    
tekstove_api.user.pm.post:
    path: "/pm/"
    defaults: { _controller:  TekstoveApiBundle:User\Pm:post}
    methods: [POST]
