tekstove_api_lyric.popularity.top.index:
    path: "/popularity/history"
    defaults: { _controller: TekstoveApiBundle:Lyric/TopPopularity:index}
    methods: [GET]

tekstove_api_lyric:
    path: "/"
    defaults: { _controller: TekstoveApiBundle:Lyric:index }
    methods: [GET]

tekstove_api_lyric_credentials:
    path: "/credentials/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric\Credentials:index }
    methods: [GET]
    
tekstove_api_lyric_credentials_new_lyric:
    path: "/credentials/"
    defaults: { _controller: TekstoveApiBundle:Lyric\Credentials:index, id: ~ }
    methods: [GET]

tekstove_api_lyric_get:
    path: "/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:get }
    methods: [GET]
    
tekstove_api_lyric_post:
    path: "/"
    defaults: { _controller: TekstoveApiBundle:Lyric:post}
    methods: [POST]
    
tekstove_api_lyric_patch:
    path: "/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:patch}
    methods: [PATCH]
    
tekstove_api_lyric.delete:
    path: "/{id}"
    defaults: { _controller: TekstoveApiBundle:Lyric:delete}
    methods: [DELETE]

