tekstove_api_forum_category_index:
    path: "/category/"
    defaults: { _controller: App\Controller\Forum\CategoryController:indexAction }
    methods: [GET]

tekstove_api_forum_category_get:
    path: "/category/{id}"
    defaults: { _controller: App\Controller\Forum\CategoryController:getAction }
    methods: [GET]

tekstove_api_forum_topic_index:
    path: "/topic/"
    defaults: { _controller: App\Controller\Forum\TopicController:indexAction }
    methods: [GET]

tekstove_api_forum_topic_:
    path: "/topic/"
    defaults: { _controller: App\Controller\Forum\TopicController:postAction }
    methods: [POST]

tekstove_api_forum_topic_get:
    path: "/topic/{id}"
    defaults: { _controller: App\Controller\Forum\TopicController:getAction }
    methods: [GET]

tekstove_api_forum_post_index:
    path: "/post/"
    defaults: { _controller: App\Controller\Forum\PostController:indexAction }
    methods: [GET]

tekstove_api_forum_post_post:
    path: "/post/"
    defaults: { _controller: App\Controller\Forum\PostController:postAction }
    methods: [POST]
