tekstove_api_lyric.popularity.top.index:
    path: "/popularity/history"
    defaults: { _controller: App\Controller\Lyric\TopPopularityController::indexAction }
    methods: [GET]

tekstove_api_lyric_credentials:
    path: "/credentials/{id}"
    defaults: { _controller: App\Controller\Lyric\CredentialsController::indexAction }
    methods: [GET]

tekstove_api_lyric_credentials_new_lyric:
    path: "/credentials/"
    defaults: { _controller: App\Controller\Lyric\CredentialsController::indexAction, id: ~ }
    methods: [GET]

tekstove_api_lyric_get:
    path: "/{id}"
    defaults: { _controller: App\Controller\LyricController::getAction }
    methods: [GET]

tekstove_api_lyric_post:
    path: "/"
    defaults: { _controller: App\Controller\LyricController::postAction }
    methods: [POST]

tekstove_api_lyric_patch:
    path: "/{id}"
    defaults: { _controller: App\Controller\LyricController::patchAction }
    methods: [PATCH]

tekstove_api_lyric.delete:
    path: "/{id}"
    defaults: { _controller: App\Controller\LyricController::deleteAction }
    methods: [DELETE]
