tekstove_api_user:
    path: "/"
    defaults: { _controller: App\Controller\UserController::indexAction }
    methods: [GET]

tekstove_api_user_register_index:
    path: "/register/"
    defaults: { _controller: App\Controller\User\RegisterController::indexAction }
    methods: [GET]

tekstove_api_user_register_post:
    path: "/register/"
    defaults: { _controller: App\Controller\User\RegisterController::postAction }
    methods: [POST]

tekstove_api_user_get:
    path: "/{id}"
    defaults: { _controller: App\Controller\UserController::getAction }
    methods: [GET]
    requirements:
        id:  \d+

tekstove_api.user.patch:
    path: "/{id}"
    defaults: { _controller:  App\Controller\UserController::patchAction }
    methods: [PATCH]

tekstove_api.user.delete:
    path: "/{id}"
    defaults: { _controller:  App\Controller\UserController::deleteAction }
    methods: [DELETE]

tekstove_api_user_login_post:
    path: "/login"
    defaults: { _controller: App\Controller\User\LoginController::postAction }
    methods: [POST]

tekstove_api_user_login_get:
    path: "/login"
    defaults: { _controller: App\Controller\User\LoginController::getAction }
    methods: [GET]

tekstove_api_user_credentials_list:
    path: "/credentials/"
    defaults: { _controller: App\Controller\UserCredentialsController::indexAction }
    methods: [GET]

tekstove_api_user_credentials:
    path: "/credentials/{id}"
    defaults: { _controller: App\Controller\UserCredentialsController::getAction }
    methods: [GET]

tekstove_api.user.pm.index:
    path: "/pm/"
    defaults: { _controller: App\Controller\User\PmController::indexAction }
    methods: [GET]

tekstove_api.user.pm.get:
    path: "/pm/{id}"
    defaults: { _controller: App\Controller\User\PmController::getAction }
    methods: [GET]

tekstove_api.user.pm.patch:
    path: "/pm/{id}"
    defaults: { _controller:  App\Controller\User\PmController::patchAction }
    methods: [PATCH]

tekstove_api.user.pm.post:
    path: "/pm/"
    defaults: { _controller:  App\Controller\User\PmController::postAction }
    methods: [POST]

tekstove_api.user.password_reset.request:
    path: "/password-reset/request"
    defaults: { _controller:  App\Controller\User\PasswordResetController::postAction }
    methods: [POST]

tekstove_api.user.password_reset.confirm:
    path: "/password-reset/confirm"
    defaults: { _controller:  App\Controller\User\PasswordResetConfirmController::postAction }
    methods: [POST]
